In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df=pd.read_csv('ischemic_stroke.csv')
pd.set_option('display.max_row', None)

In [3]:
del np.where(df['# of Cases'] > 1000)

(array([   0,    1,  555,  556, 1105, 1106, 1654, 1655]),)

In [8]:
df.drop(['OSHPDID', 'Location 1'], axis = 1, inplace = True)

In [15]:
df = df[df['# of Cases'] <= 1000]

In [29]:
df['County'].value_counts()

County
Los Angeles        546
Orange             139
San Diego          120
Riverside          114
San Bernardino     104
Alameda             98
Santa Clara         72
San Francisco       72
Sacramento          72
Contra Costa        64
San Joaquin         56
Sonoma              54
Ventura             52
San Mateo           48
Kern                48
Fresno              34
Solano              33
San Luis Obispo     32
Stanislaus          30
Santa Barbara       24
Placer              24
Marin               24
Monterey            24
Butte               24
Mendocino           23
Tulare              22
Humboldt            21
Yolo                16
Imperial            16
Napa                16
Santa Cruz          16
Shasta              16
El Dorado           11
Siskiyou             9
Tuolumne             8
Del Norte            8
Tehama               8
Calaveras            8
Nevada               8
Kings                8
Lake                 8
Madera               8
San Benito           8
Merc

In [ ]:
#Perform descriptive statistics on counties with highest hospitals, mortality and readmission rate, cases, risk adjusted rate, 
#counties with the highest hospital rating, graphs and charts

In [24]:
df['']

Hospital         AHMC Anaheim Regional Medical Center  \
County                                                  
Alameda                                             0   
Amador                                              0   
Butte                                               0   
Calaveras                                           0   
Contra Costa                                        0   
Del Norte                                           0   
El Dorado                                           0   
Fresno                                              0   
Humboldt                                            0   
Imperial                                            0   
Kern                                                0   
Kings                                               0   
Lake                                                0   
Los Angeles                                         0   
Madera                                              0   
Marin                                               0   
Mendocino                                           0   
Merced                                              0   
Monterey                                            0   
Napa                                                0   
Nevada                                              0   
Orange                                              8   
Placer                                              0   
Riverside                                           0   
Sacramento                                          0   
San Benito                                          0   
San Bernardino                                      0   
San Diego                                           0   
San Francisco                                       0   
San Joaquin                                         0   
San Luis Obispo                                     0   
San Mateo                                           0   
Santa Barbara                                       0   
Santa Clara                                         0   
Santa Cruz                                          0   
Shasta                                              0   
Siskiyou                                            0   
Solano                                              0   
Sonoma                                              0   
Stanislaus                                          0   
Tehama                                              0   
Tulare                                              0   
Tuolumne                                            0   
Ventura                                             0   
Yolo                                                0   
Yuba                                                0   
All                                                 8   

Hospital         Adventist Medical Center  Adventist Medical Center - Reedley  \
County                                                                          
Alameda                                 0                                   0   
Amador                                  0                                   0   
Butte                                   0                                   0   
Calaveras                               0                                   0   
Contra Costa                            0                                   0   
Del Norte                               0                                   0   
El Dorado                               0                                   0   
Fresno                                  0                                   2   
Humboldt                                0                                   0   
Imperial                                0                                   0   
Kern                                    0                                   0   
Kings                                   8                                   0   
Lake                                    0                               

In [17]:
df.head()

Year   County                                           Hospital  \
2  2011-2012  Alameda                                   Alameda Hospital   
3  2011-2012  Alameda                                   Alameda Hospital   
4  2011-2012  Alameda  Alta Bates Summit Medical Center – Alta Bate...   
5  2011-2012  Alameda  Alta Bates Summit Medical Center – Alta Bate...   
6  2011-2012  Alameda                                Eden Medical Center   

              Measure  Risk Adjusted Rate  # of Deaths/Readmissions  \
2  30-day Readmission               18.66                      18.0   
3    30-day Mortality               12.22                      12.0   
4  30-day Readmission               11.91                      34.0   
5    30-day Mortality                9.82                      24.0   
6    30-day Mortality               12.36                      53.0   

   # of Cases Hospital Ratings  
2        92.0      As Expected  
3        95.0      As Expected  
4       281.0      As Expected  
5       287.0      As Expected  
6       399.0      As Expected

In [7]:
df.head()

Year   County                                           Hospital  \
0  2011-2012      NaN                                          Statewide   
1  2011-2012      NaN                                          Statewide   
2  2011-2012  Alameda                                   Alameda Hospital   
3  2011-2012  Alameda                                   Alameda Hospital   
4  2011-2012  Alameda  Alta Bates Summit Medical Center – Alta Bate...   

     OSHPDID             Measure  Risk Adjusted Rate  \
0        NaN    30-day Mortality               10.55   
1        NaN  30-day Readmission               12.80   
2  106010735  30-day Readmission               18.66   
3  106010735    30-day Mortality               12.22   
4  106010739  30-day Readmission               11.91   

   # of Deaths/Readmissions  # of Cases Hospital Ratings  \
0                    7406.0     70213.0              NaN   
1                    8527.0     66612.0              NaN   
2                      18.0        92.0      As Expected   
3                      12.0        95.0      As Expected   
4                      34.0       281.0      As Expected   

                Location 1  
0                      NaN  
1                      NaN  
2  (37.762953, -122.25362)  
3  (37.762953, -122.25362)  
4   (37.85633, -122.25784)

In [8]:
np.where(df.isnull())

(array([   0,    0,    0,    0,    1,    1,    1,    1,  279,  279,  279,
         279,  501,  501,  501,  501,  555,  555,  555,  556,  556,  556,
         608,  608,  608,  608,  635,  635,  635,  635,  742,  742,  742,
         742, 1105, 1105, 1106, 1106, 1174, 1174, 1174, 1174, 1188, 1188,
        1188, 1188, 1221, 1221, 1221, 1221, 1345, 1345, 1345, 1345, 1592,
        1592, 1592, 1592, 1654, 1654, 1655, 1655]),
 array([1, 3, 8, 9, 1, 3, 8, 9, 5, 6, 7, 8, 5, 6, 7, 8, 3, 8, 9, 3, 8, 9,
        5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8, 8, 9, 8, 9, 5, 6, 7, 8, 5, 6,
        7, 8, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8, 8, 9, 8, 9]))

In [41]:
df.index

Index([   2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
       ...
       2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187],
      dtype='int64', length=2170)

In [42]:
df.head()

Year   County                                           Hospital  \
2  2011-2012  Alameda                                   Alameda Hospital   
3  2011-2012  Alameda                                   Alameda Hospital   
4  2011-2012  Alameda  Alta Bates Summit Medical Center – Alta Bate...   
5  2011-2012  Alameda  Alta Bates Summit Medical Center – Alta Bate...   
6  2011-2012  Alameda                                Eden Medical Center   

              Measure  Risk Adjusted Rate  # of Deaths/Readmissions  \
2  30-day Readmission               18.66                      18.0   
3    30-day Mortality               12.22                      12.0   
4  30-day Readmission               11.91                      34.0   
5    30-day Mortality                9.82                      24.0   
6    30-day Mortality               12.36                      53.0   

   # of Cases Hospital Ratings  
2        92.0      As Expected  
3        95.0      As Expected  
4       281.0      As Expected  
5       287.0      As Expected  
6       399.0      As Expected

In [46]:
df.to_csv('E:\\cleaned_ischemic_stroke.csv')